name: 'Code sign a file with pfx certificate'
description: 'Sign a file with a pfx certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
  password:
    description: 'The password'
    required: false
  certificatename:
    description: 'The certificate name'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
